name: ggg_app
description: Go Garbage Grabber mobile/web app
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.2
  http_parser: ^4.0.2
  file_picker: ^10.3.3
  camera: ^0.11.0+2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # If you have assets/fonts, re-add them here under flutter:
  # assets:
  #   - assets/
