platform :ios, '13.0'

# Keep CocoaPods deterministic
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

# Point to Flutter's pod helper (this defines flutter_post_install)
# RIGHT
require_relative 'Flutter/podhelper'

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_post_install(installer)   # <-- this is what was "undefined" before
end
